import { describe, expect, it } from 'vitest'
import { createGeminiImageFunction } from '../geminiImage'
import { createGeminiLlmFunction } from '../geminiLlm'
import { createLocalTransformFunctions } from '../localTransforms'
import { createOpenAIImageFunction } from '../openaiImage'
import { createOpenAILlmFunction } from '../openaiLlm'
import { createRequestFunction } from '../requestFunction'
import type { GenerationFunction, Resource } from '../types'
import {
  createRunSnapshot,
  generatedResourceSourceForRun,
  isRunGeneratedResource,
  runProviderForFunction,
} from './runSnapshot'

const now = '2026-06-23T00:00:00.000Z'

const comfyFunction = (): GenerationFunction => ({
  id: 'fn_comfy',
  name: 'Comfy Image',
  category: 'Image',
  workflow: {
    format: 'comfyui_api_json',
    rawJson: {
      '1': {
        class_type: 'SaveImage',
        inputs: {},
      },
    },
  },
  inputs: [
    {
      key: 'prompt',
      label: 'Prompt',
      type: 'text',
      required: true,
      bind: { path: '1.inputs.text' },
    },
  ],
  outputs: [
    {
      key: 'image',
      label: 'Image',
      type: 'image',
      bind: { path: '1.images' },
      extract: { source: 'history' },
    },
  ],
  createdAt: now,
  updatedAt: now,
})

describe('runSnapshot', () => {
  it('maps every function format to a run provider', () => {
    const localFunction = createLocalTransformFunctions(now)[0]!

    expect(runProviderForFunction(comfyFunction())).toBe('comfyui')
    expect(runProviderForFunction(createOpenAILlmFunction(now))).toBe('openai_llm')
    expect(runProviderForFunction(createGeminiLlmFunction(now))).toBe('gemini_llm')
    expect(runProviderForFunction(createOpenAIImageFunction(now))).toBe('openai_image')
    expect(runProviderForFunction(createGeminiImageFunction(now))).toBe('gemini_image')
    expect(runProviderForFunction(createRequestFunction('fn_request', 'Webhook Lookup', now))).toBe('http_request')
    expect(runProviderForFunction(localFunction)).toBe('local_transform')
  })

  it('creates a normalized run snapshot from a function definition', () => {
    const functionDef = createRequestFunction('fn_request', 'Webhook Lookup', now)

    const snapshot = createRunSnapshot({
      id: 'run_1',
      functionDef,
      inputRefs: {
        q: { resourceId: 'res_prompt', type: 'text' },
      },
      inputValuesSnapshot: {
        q: {
          key: 'q',
          label: 'Query',
          type: 'text',
          required: true,
          source: 'resource',
          value: 'kitchen',
          resourceId: 'res_prompt',
          resourceName: 'Prompt',
        },
      },
      primitiveParams: { limit: 3 },
      runIndex: 2,
      runTotal: 4,
      outputRefs: {
        result: [{ resourceId: 'res_result', type: 'text' }],
      },
      endpointId: 'endpoint_local',
      requestSnapshot: { url: 'https://example.com/search?q=kitchen' },
      status: 'queued',
      now,
    })

    expect(snapshot).toMatchObject({
      id: 'run_1',
      functionId: 'fn_request',
      functionName: 'Webhook Lookup',
      provider: 'http_request',
      inputRefs: {
        q: { resourceId: 'res_prompt', type: 'text' },
      },
      primitiveParams: { limit: 3 },
      runIndex: 2,
      runTotal: 4,
      outputRefs: {
        result: [{ resourceId: 'res_result', type: 'text' }],
      },
      endpointId: 'endpoint_local',
      requestSnapshot: { url: 'https://example.com/search?q=kitchen' },
      seedPatchLog: [],
      taskIds: [],
      status: 'queued',
      createdAt: now,
      updatedAt: now,
    })

    functionDef.name = 'Changed Later'
    expect(snapshot.functionSnapshot.name).toBe('Webhook Lookup')
  })

  it('derives generated resource source metadata from run id and output key only', () => {
    const source = generatedResourceSourceForRun({
      runId: 'run_1',
      outputKey: 'image',
      parentResourceId: 'res_parent',
    })

    expect(source).toEqual({
      kind: 'function_output',
      runId: 'run_1',
      outputKey: 'image',
      parentResourceId: 'res_parent',
    })
    expect(source).not.toHaveProperty('functionNodeId')
    expect(source).not.toHaveProperty('resultGroupNodeId')
  })

  it('recognizes output resources generated by a run snapshot', () => {
    const resource: Resource = {
      id: 'res_image',
      type: 'image',
      value: {
        assetId: 'asset_image',
        url: '/assets/asset_image.png',
        filename: 'asset_image.png',
        mimeType: 'image/png',
        sizeBytes: 1024,
      },
      source: generatedResourceSourceForRun({ runId: 'run_1', outputKey: 'image' }),
      metadata: { createdAt: now },
    }

    expect(isRunGeneratedResource(resource)).toBe(true)
    expect(isRunGeneratedResource({ ...resource, source: { kind: 'function_output', outputKey: 'image' } })).toBe(false)
  })
})
